version: "3.8"

services:
  server_siga:
    container_name: server_siga
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - siga_db:/app/server/src/db
      - siga_config:/app/server/src/config
    networks:
      - siga_network
  nginx_siga:
    container_name: nginx_siga
    image: nginx
    restart: always
    ports:
      - "3010:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - siga_network
networks:
  siga_network:
    driver: bridge

volumes:
  siga_db:
  siga_config:
