version: "3.8"

services:
  server_siga:
    container_name: server_siga
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./db:/app/db
      - ./config:/app/config
    networks:
      - siga_network
networks:
  siga_network:
    driver: bridge